/*
 * This file is part of OpenAstexViewer.
 *
 * OpenAstexViewer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenAstexViewer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with OpenAstexViewer.  If not, see <http://www.gnu.org/licenses/>.
 */


//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Jan 29 17:13:22 GMT 2004
//----------------------------------------------------

package astex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DASH = 6;
  public static final int EVALUATE = 49;
  public static final int GRAPH = 39;
  public static final int AND = 11;
  public static final int VDW = 75;
  public static final int BACKFACE = 101;
  public static final int CHAIN = 43;
  public static final int USER = 111;
  public static final int error = 1;
  public static final int LINES = 25;
  public static final int LPAREN = 4;
  public static final int RESIDUE = 33;
  public static final int APPEND = 90;
  public static final int XRAY = 114;
  public static final int WIDE = 62;
  public static final int PRINT = 110;
  public static final int CONTOUR = 87;
  public static final int SET = 84;
  public static final int CONTACT = 22;
  public static final int BOND_WIDTH = 32;
  public static final int MAP = 42;
  public static final int CLIP = 73;
  public static final int TRUE = 122;
  public static final int COLOR_BY_RAINBOW = 68;
  public static final int SKELETON = 109;
  public static final int BALL_RADIUS = 30;
  public static final int DEFAULT = 17;
  public static final int DISPLAY = 54;
  public static final int RECTANGULAR = 97;
  public static final int FETCH = 50;
  public static final int INSERTION = 34;
  public static final int LABELLED = 18;
  public static final int CHARGE = 76;
  public static final int EXCLUDE = 91;
  public static final int MATRIX = 86;
  public static final int NOT = 13;
  public static final int RPAREN = 5;
  public static final int DOTSURFACE = 58;
  public static final int SEQUENTIAL = 35;
  public static final int FORCEFIELD = 108;
  public static final int CYLINDER_RADIUS = 31;
  public static final int SPHERE = 23;
  public static final int ALL = 14;
  public static final int DOUBLE = 127;
  public static final int CLEAR = 83;
  public static final int OBJECT = 52;
  public static final int CENTER = 79;
  public static final int BACKGROUND = 102;
  public static final int CYLINDERS = 26;
  public static final int DISPLAYED = 19;
  public static final int DOLLAR = 8;
  public static final int AROUND = 44;
  public static final int NAME = 37;
  public static final int MODELLING = 107;
  public static final int INVERT = 89;
  public static final int ARG = 121;
  public static final int BYRESIDUE = 38;
  public static final int DISTANCE = 80;
  public static final int COMMA = 7;
  public static final int ANGLE = 81;
  public static final int ANIMATE = 105;
  public static final int LOAD = 60;
  public static final int ATTRIBUTE = 125;
  public static final int INTEGER = 126;
  public static final int SELECT = 88;
  public static final int ID = 20;
  public static final int COMPOSITE = 36;
  public static final int TEXTURE = 93;
  public static final int ACTIVE_SITE = 106;
  public static final int OR = 12;
  public static final int COLOR_BY_ENERGY = 67;
  public static final int REPAINT = 104;
  public static final int ON = 70;
  public static final int ENVIRONMENT = 113;
  public static final int STICKS = 27;
  public static final int TOGGLE = 72;
  public static final int STICK_RADIUS = 28;
  public static final int OPERATOR = 124;
  public static final int ZAP = 85;
  public static final int RADIUS = 74;
  public static final int LCURLY = 9;
  public static final int INCREASE = 77;
  public static final int MOLECULE = 40;
  public static final int VIEW = 118;
  public static final int TRANSPARENCY = 95;
  public static final int IONS = 48;
  public static final int ACTIVE = 112;
  public static final int SEMI = 3;
  public static final int FALSE = 123;
  public static final int LIPOPHILICITY = 100;
  public static final int WRITE = 117;
  public static final int SURFACE = 55;
  public static final int CURVATURE = 98;
  public static final int STICK_COLOR = 29;
  public static final int LIGHT = 94;
  public static final int ELECTROSTATIC = 99;
  public static final int CURRENT = 16;
  public static final int HBOND = 116;
  public static final int TO = 82;
  public static final int MOLEXACT = 41;
  public static final int COLOR = 63;
  public static final int SPHERES = 24;
  public static final int COLON = 2;
  public static final int DEFINE = 92;
  public static final int RCURLY = 10;
  public static final int LAZY = 61;
  public static final int ANASURFACE = 59;
  public static final int COLOR_BY_CHAIN = 65;
  public static final int SCHEMATIC = 120;
  public static final int DNA = 47;
  public static final int SECSTRUC = 119;
  public static final int AMINOACID = 46;
  public static final int REMOVE = 53;
  public static final int COLOR_BY_BVALUE = 66;
  public static final int ATOM = 21;
  public static final int SIMPLE = 96;
  public static final int COLOR_BY_BVALUE_RANGE = 69;
  public static final int PROPERTY = 57;
  public static final int COLOR_BY_ATOM = 64;
  public static final int DECREASE = 78;
  public static final int EOF = 0;
  public static final int LABEL = 51;
  public static final int STRING = 128;
  public static final int NONE = 15;
  public static final int SOLVENT = 45;
  public static final int OFF = 71;
  public static final int UNDEFINE = 103;
  public static final int FIXED = 115;
  public static final int CONTEXT = 56;
}

